apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGl1ZXpjcGRh
  CLOUDINARY_KEY: MTY4MTQ2MzczMzEyOTU3
  CLOUDINARY_SECRET: ZnBnVGlMaENlV015ZDNNbklTZmNucllRZnFz
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljM0poZG1GdU5ERWlMQ0poSWpvaVkyMXBZblo2TVdreU1IRnNhekpzYzJobGJuWnZkR1pwTXlKOS5ZY2NjdzZJWDVMZFBDN2pVMEpSQmJR
  DB_URL:bW9uZ29kYitzcnY6Ly9zcmF2YW5rZ3NldHR5X2RiX3VzZXI6TnF0cUpHNWRlOVF2Vlp4aUBjbHVzdGVyMC51MmlmaXRwLm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw 
  SECRET: bXVzdGFmYQ==
